# packages in environment at /home/zarar/miniconda3/envs/leela:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.11.0             pyhd3eb1b0_1  
argon2-cffi               20.1.0           py37h7b6447c_1  
astor                     0.8.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10             py37h28b3542_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.9.3                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    1.5.0                    pypi_0    pypi
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2021.1.19            h06a4308_0  
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.0                    pypi_0    pypi
certifi                   2020.12.5        py37h06a4308_0  
cffi                      1.14.4           py37h261ae71_0  
chardet                   4.0.0                    pypi_0    pypi
chess                     1.3.3                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
cupti                     10.0.130                      0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py37_0  
expat                     2.2.10               he6710b0_2  
fire                      0.3.1                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
gast                      0.3.3                    pypi_0    pypi
glib                      2.66.1               h92f7085_0  
google-auth               1.24.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
google-pasta              0.2.0                      py_0  
grpcio                    1.32.0                   pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
h5py                      2.10.0           py37hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
html5lib                  0.9999999                pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
importlib-metadata        3.3.0                    pypi_0    pypi
importlib_metadata        2.0.0                         1  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py37h5ca1d4c_0  
ipython                   7.19.0           py37hb070fc8_1  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2             pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.7.0            py37h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
keras-applications        1.0.8                      py_1  
keras-preprocessing       1.1.2                    pypi_0    pypi
lczero-tools              0.2                       dev_0    <develop>
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.13.0.1             hd408876_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
markdown                  3.3.3            py37h06a4308_0  
markupsafe                1.1.1            py37h14c3975_1  
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py37_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.3              pyhd3eb1b0_0  
notebook                  6.2.0            py37h06a4308_0  
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1i               h27cfd23_0  
opt-einsum                3.3.0                    pypi_0    pypi
opt_einsum                3.1.0                      py_0  
packaging                 20.9               pyhd3eb1b0_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.3            py37h06a4308_1  
parso                     0.7.1                    pypi_0    pypi
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       20.3.3           py37h06a4308_0  
prometheus_client         0.9.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
protobuf                  3.12.1                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2  
pygments                  2.7.3                    pypi_0    pypi
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.17.3           py37h7b6447c_0  
python                    3.7.9                h7579374_0  
python-chess              0.23.10                  pypi_0    pypi
python-dateutil           2.8.1              pyhd3eb1b0_0  
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0           py37h2531618_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scipy                     1.5.2            py37h0b6359f_0  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                51.0.0           py37h06a4308_2  
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0           py37h06a4308_0  
soupsieve                 2.1                      pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.4.0                    pypi_0    pypi
tensorflow-base           2.0.0           gpu_py37h0ec5d1f_0  
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorflow-gpu            2.0.3                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.2            py37h06a4308_0  
testpath                  0.4.4              pyhd3eb1b0_0  
tk                        8.6.10               hbc83047_0  
torch                     1.7.1                    pypi_0    pypi
tornado                   6.1              py37h27cfd23_0  
tqdm                      4.56.0                   pypi_0    pypi
traitlets                 5.0.5              pyhd3eb1b0_0  
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.12.1           py37h7b6447c_1  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.3                he6710b0_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
